# Generated by Django 3.0.3 on 2020-03-29 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Agent', '0001_initial'),
        ('moborise', '0002_auto_20200329_1439'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('post_id', models.IntegerField(default='0')),
                ('Username', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('to', models.CharField(max_length=100)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TheUser', to='Agent.Agentuploads')),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply', models.TextField()),
                ('Username', models.CharField(max_length=100)),
                ('post_id', models.IntegerField(default='0')),
                ('time', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('to', models.CharField(max_length=100)),
                ('rep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reply', to='moborise.Comment')),
            ],
        ),
    ]
