# Generated by Django 3.0.3 on 2020-03-29 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moborise', '0003_comment_reply'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usertype',
            old_name='About',
            new_name='Aboutt',
        ),
    ]
