# Generated by Django 3.0.3 on 2020-03-29 13:39

import Agent.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agentuploads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=Agent.models.user_directory_path)),
                ('filename', models.CharField(blank=True, max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('property_Name', models.CharField(max_length=100)),
                ('property_Address', models.CharField(max_length=100)),
                ('property_Location', models.CharField(max_length=100)),
                ('property_Description', models.CharField(max_length=100)),
                ('property_Type', models.CharField(max_length=100)),
                ('price', models.IntegerField(default=0)),
                ('verify', models.TextField(default='Not verified', max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(max_length=150)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='uploadsfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='gallery/')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='picture', to='Agent.Agentuploads')),
            ],
        ),
    ]
